#!/bin/bash
# =============================================================================
# Cleanup script: removes all stale files from previous training runs.
#
# These files are from:
#   - Old RT checkpoints with wrong naming (no kuairec_ prefix)
#   - Old PT results corrupted by backwards diversity loss bug
#   - Old experimental directories (hyperopt, duorec, etc.)
#   - Old logs from previous runs
#   - Stale tensorboard logs (now using /tmp on remote)
#
# KEEPS:
#   - baseline_results_* (valid baseline evaluations)
#   - save_gru4rec_*, save_sasrec_*, save_bert4rec_* (baseline checkpoints)
#   - KuaiRec_variants/, KuaiRec/, Yelp/, Baselines/ (data)
#   - Current scripts: train_all.sh, train_rt_all.sh, eval_all.sh
#
# Usage:
#   bash cleanup_stale.sh           # delete (with confirmation)
#   bash cleanup_stale.sh -f        # force delete (no confirmation)
# =============================================================================

FORCE=false
if [ "$1" == "-f" ]; then
    FORCE=true
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

# Files/directories to delete
STALE_DIRS=(
    # Old RT checkpoints (wrong naming, trained with old code)
    "save_rt_highest_individual"
    "save_rt_yelp"

    # Old PT results (corrupted by backwards div loss)
    "remote_results"

    # Old experimental directories
    "save_consec"
    "save_div_final"
    "save_duorec"
    "save_duorec_v2"
    "save_duorec_v3"
    "save_final"
    "save_hyperopt"
    "save_hyperopt_div"
    "save_hyperopt_final"
    "save_optimized"

    # Stale tensorboard logs (now using /tmp on remote)
    "tensorboard_log"

    # Old baseline_results (pre-NDCG fix, empty/placeholder dir)
    "baseline_results"
)

STALE_LOGS=(
    "train_output.log"
    "train_output_v2.log"
    "train_output_v3.log"
    "test_output_epoch25.log"
    # Old eval logs (will be regenerated by eval_all.sh)
    "eval_gru4rec_kuairec_first_average.log"
    "eval_gru4rec_kuairec_first_individual.log"
    "eval_gru4rec_kuairec_highest_average.log"
    "eval_gru4rec_kuairec_highest_individual.log"
    "eval_sasrec_kuairec_first_average.log"
    "eval_sasrec_kuairec_first_individual.log"
    "eval_sasrec_kuairec_highest_average.log"
    "eval_sasrec_kuairec_highest_individual.log"
    "eval_bert4rec_kuairec_first_average.log"
    "eval_bert4rec_kuairec_first_individual.log"
    "eval_bert4rec_kuairec_highest_average.log"
    "eval_bert4rec_kuairec_highest_individual.log"
)

STALE_SCRIPTS=(
    # Obsolete scripts replaced by train_all.sh / train_rt_all.sh / eval_all.sh
    "train_all_variants.sh"
    "cleanup_remote.sh"
    "generate_all_datasets.sh"
    "generate_dataset_grid.sh"
)

echo "############################################################"
echo "# Stale File Cleanup"
echo "############################################################"
echo ""

# Calculate total size
TOTAL_SIZE=0
echo "Directories to delete:"
for dir in "${STALE_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        SIZE=$(du -sh "$dir" 2>/dev/null | awk '{print $1}')
        echo "  [DIR]  ${dir} (${SIZE})"
    fi
done

echo ""
echo "Logs to delete:"
for log in "${STALE_LOGS[@]}"; do
    if [ -f "$log" ]; then
        SIZE=$(du -sh "$log" 2>/dev/null | awk '{print $1}')
        echo "  [LOG]  ${log} (${SIZE})"
    fi
done

echo ""
echo "Scripts to delete:"
for script in "${STALE_SCRIPTS[@]}"; do
    if [ -f "$script" ]; then
        echo "  [SH]   ${script}"
    fi
done

echo ""

# Confirm deletion
if [ "$FORCE" != true ]; then
    read -p "Delete all listed files? (y/N) " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Delete directories
for dir in "${STALE_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        echo "Removing ${dir}..."
        rm -rf "$dir"
    fi
done

# Delete logs
for log in "${STALE_LOGS[@]}"; do
    if [ -f "$log" ]; then
        echo "Removing ${log}..."
        rm -f "$log"
    fi
done

# Delete scripts
for script in "${STALE_SCRIPTS[@]}"; do
    if [ -f "$script" ]; then
        echo "Removing ${script}..."
        rm -f "$script"
    fi
done

echo ""
echo "############################################################"
echo "# Cleanup complete!"
echo "############################################################"
echo ""
echo "Remaining save directories:"
ls -d save_* 2>/dev/null || echo "  (none)"
echo ""
echo "Next steps:"
echo "  1. bash train_rt_all.sh          # train RT models (must be first)"
echo "  2. bash train_all.sh             # train PT models (depends on RT)"
echo "  3. bash eval_all.sh              # evaluate all models"
